USE TourMaster
GO

DROP TABLE IF EXISTS Tourist;
DROP TABLE IF EXISTS Transportation;
DROP TABLE IF EXISTS RoomReservation;
DROP TABLE IF EXISTS Tour;
DROP TABLE IF EXISTS Transporter;
DROP TABLE IF EXISTS Hotel;
DROP TABLE IF EXISTS Client;